apiVersion: v1
kind: Pod
metadata:
    name: quota-mem-cpu-demo-2
spec:
    containers:
    - name: quota-mem-cpu-demo-2-cotr
      image: nginx:latest
      resources:
        limits:
          memory: "1Gi"
          cpu: "800m"
        requests:
          memory: "700Mi"
          cpu: "400m"